# Generated by Django 2.0.6 on 2018-06-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jedi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Order')),
                ('questions', models.ManyToManyField(through='selection_committee.QAns', to='selection_committee.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Youngling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(default='folko93@mail.ru', max_length=254)),
                ('planet_habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Planet')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Younglings', to='selection_committee.Jedi')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='youngling',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Youngling'),
        ),
        migrations.AddField(
            model_name='qans',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Question'),
        ),
        migrations.AddField(
            model_name='qans',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Test'),
        ),
        migrations.AddField(
            model_name='jedi',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Order'),
        ),
        migrations.AddField(
            model_name='jedi',
            name='planet_stud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Planet'),
        ),
    ]
