# Generated by Django 2.0.6 on 2018-06-08 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('selection_committee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='youngling',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='selection_committee.Youngling'),
        ),
    ]
